//categoriesName = ['category1', 'category2', 'category3', 'category4', 'category5', 'all'];
const articlesInfo = [
  {
    img: 'assets/img/articles/a1.webp',
    name: 'Name article 1',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: 'articles/article1.html',
    cat: categoriesName[0],
    slide: true,
  },
  {
    img: 'assets/img/articles/a2.webp',
    name: 'Name article 2',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[1],
    slide: true,
  },
  {
    img: 'assets/img/articles/a3.webp',
    name: 'Name article 3',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[2],
    slide: false,
  },
  {
    img: 'assets/img/articles/a4.webp',
    name: 'Name article 4',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[3],
    slide: true,
  },
  {
    img: 'assets/img/articles/a5.webp',
    name: 'Name article 5',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[0],
    slide: true,
  },
  {
    img: 'assets/img/articles/a6.webp',
    name: 'Name article 6',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[3],
    slide: true,
  },
  {
    img: 'assets/img/articles/a7.webp',
    name: 'Name article 7',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[4],
    slide: false,
  },
  {
    img: 'assets/img/articles/a8.webp',
    name: 'Name article 8',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[1],
    slide: false,
  },
  {
    img: 'assets/img/articles/a9.webp',
    name: 'Name article 9',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[0],
    slide: false,
  },
  {
    img: 'assets/img/articles/a10.webp',
    name: 'Name article 10',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[4],
    slide: false,
  },
  {
    img: 'assets/img/articles/a11.webp',
    name: 'Name article 11',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: categoriesName[0],
    slide: false,
  },
];
