const articlesInfo = [
  {
    img: 'assets/img/articles/a1.webp',
    name: 'Name article 1',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category1',
  },
  {
    img: 'assets/img/articles/a2.webp',
    name: 'Name article 2',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category2',
  },
  {
    img: 'assets/img/articles/a3.webp',
    name: 'Name article 3',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category3',
  },
  {
    img: 'assets/img/articles/a4.webp',
    name: 'Name article 4',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category4',
  },
  {
    img: 'assets/img/articles/a5.webp',
    name: 'Name article 5',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category1',
  },
  {
    img: 'assets/img/articles/a6.webp',
    name: 'Name article 6',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category4',
  },
  {
    img: 'assets/img/articles/a7.webp',
    name: 'Name article 7',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category2',
  },
  {
    img: 'assets/img/articles/a8.webp',
    name: 'Name article 8',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category2',
  },
  {
    img: 'assets/img/articles/a9.webp',
    name: 'Name article 9',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category1',
  },
  {
    img: 'assets/img/articles/a10.webp',
    name: 'Name article 10',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category1',
  },
  {
    img: 'assets/img/articles/a11.webp',
    name: 'Name article 11',
    text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    link: '#',
    cat: 'category1',
  },
];
