//categoriesName = ['category1', 'category2', 'category3', 'category4', 'category5', 'all'];
const catInfo = [
  {
    img: 'assets/img/categories/c1.webp',
    name: categoriesName[0],
    link: `catigories.html?cat=${categoriesName[0]}`,
    classesImgLink: ['category__image'],
    classesLink: ['category__link'],
    classesBtn: ['category__arrow'],
  },
  {
    img: 'assets/img/categories/c2.webp',
    name: categoriesName[1],
    link: `catigories.html?cat=${categoriesName[1]}`,
    classesImgLink: ['category__image', 'category2'],
    classesLink: ['category__link', 'category2'],
    classesBtn: ['category__arrow', 'category2'],
  },
  {
    img: 'assets/img/categories/c3.webp',
    name: categoriesName[2],
    link: `catigories.html?cat=${categoriesName[2]}`,
    classesImgLink: ['category__image', 'category3'],
    classesLink: ['category__link', 'category3'],
    classesBtn: ['category__arrow', 'category3'],
  },
  {
    img: 'assets/img/categories/c4.webp',
    name: categoriesName[3],
    link: `catigories.html?cat=${categoriesName[3]}`,
    classesImgLink: ['category__image', 'category4'],
    classesLink: ['category__link', 'category4'],
    classesBtn: ['category__arrow', 'category4'],
  },
  {
    img: 'assets/img/categories/c5.webp',
    name: categoriesName[4],
    link: `catigories.html?cat=${categoriesName[4]}`,
    classesImgLink: ['category__image', 'category5'],
    classesLink: ['category__link', 'category5'],
    classesBtn: ['category__arrow', 'category5'],
  },
  {
    img: 'assets/img/categories/c6.webp',
    name: categoriesName[5],
    link: `catigories.html?cat=${categoriesName[5]}`,
    classesImgLink: ['category__image', 'all'],
    classesLink: ['category__link', 'all'],
    classesBtn: ['category__arrow', 'all'],
  },
];
