const catInfo = [
  {
    img: 'assets/img/categories/c1.webp',
    name: ' category1',
    link: 'catigories.html?cat=category1',
    classesImgLink: ['category__image', 'category1'],
    classesLink: ['category__link', 'category1'],
    classesBtn: ['category__arrow', 'category1'],
  },
  {
    img: 'assets/img/categories/c2.webp',
    name: ' category2 ',
    link: 'catigories.html?cat=category2',
    classesImgLink: ['category__image', 'category2'],
    classesLink: ['category__link', 'category2'],
    classesBtn: ['category__arrow', 'category2'],
  },
  {
    img: 'assets/img/categories/c3.webp',
    name: ' category3 ',
    link: 'catigories.html?cat=category3',
    classesImgLink: ['category__image', 'category3'],
    classesLink: ['category__link', 'category3'],
    classesBtn: ['category__arrow', 'category3'],
  },
  {
    img: 'assets/img/categories/c4.webp',
    name: ' category4 ',
    link: 'catigories.html?cat=category4',
    classesImgLink: ['category__image', 'category4'],
    classesLink: ['category__link', 'category4'],
    classesBtn: ['category__arrow', 'category4'],
  },
  {
    img: 'assets/img/categories/c5.webp',
    name: ' category5 ',
    link: 'catigories.html?cat=category5',
    classesImgLink: ['category__image', 'category5'],
    classesLink: ['category__link', 'category5'],
    classesBtn: ['category__arrow', 'category5'],
  },
  {
    img: 'assets/img/categories/c6.webp',
    name: ' all ',
    link: 'catigories.html?cat=all',
    classesImgLink: ['category__image', 'all'],
    classesLink: ['category__link', 'all'],
    classesBtn: ['category__arrow', 'all'],
  },
];
